import { useState } from "react";
import { T, SECS, iS, selS, smI } from "../tokens";
import { SEC_COLS } from "../data/constants";
import { SecHead, Nts, Strip, PrimaryCard, Disc, ScoreRow, Decision, Chk } from "../components/primitives";
import { Findings, AIBtn, InvTable } from "../components/shared";

function SecView({ secTools, setSecTools, secFindings, setSecFindings }) {
  const _n = useState("11 vendors→5. ASA 38 sites EOS. ZT low, board FY27.\n2400+ FW rules ~40% unused. No CASB — 340+ shadow apps."); const notes = _n[0]; const setNotes = _n[1];
  const _sa = useState([{ label: "SWG", score: 1 }, { label: "CASB", score: 1 }, { label: "ZTNA", score: 1 }, { label: "DLP", score: 2 }, { label: "FWaaS", score: 2 }, { label: "Remote", score: 2 }, { label: "Branch", score: 1 }, { label: "Policy", score: 1 }]); const sase = _sa[0]; const setSase = _sa[1];
  const _ve = useState([{ name: "Cisco ASA", decision: "Replace", reason: "EOS" }, { name: "Zscaler", decision: "Evaluate", reason: "vs FortiSASE" }, { name: "CrowdStrike", decision: "Retain", reason: "Strong EDR" }, { name: "Splunk", decision: "Replace", reason: "→FortiSIEM" }, { name: "Proofpoint", decision: "Retain", reason: "OK" }, { name: "Tenable", decision: "Replace", reason: "→FortiAnalyzer" }]); const vendors = _ve[0]; const setVendors = _ve[1];
  const _zt = useState([{ label: "Single IdP", done: false, sub: "AD+Okta" }, { label: "MFA all users", done: true, sub: "Okta" }, { label: "Device posture", done: false, sub: "None" }, { label: "Microsegmentation", done: false, sub: "Flat" }, { label: "ZTNA replaces VPN", done: false, sub: "2100 split-tunnel" }, { label: "Least-privilege", done: false, sub: "Phase 1" }]); const zt = _zt[0]; const setZt = _zt[1];
  const _sd1 = useState(""); const sd1 = _sd1[0]; const setSd1 = _sd1[1];
  const _sd2 = useState(""); const sd2 = _sd2[0]; const setSd2 = _sd2[1];
  const _trig = useState(""); const trigger = _trig[0]; const setTrigger = _trig[1];
  const _trigNote = useState(""); const trigNote = _trigNote[0]; const setTrigNote = _trigNote[1];
  const _vision = useState(""); const vision = _vision[0]; const setVision = _vision[1];
  const _met1 = useState(""); const met1 = _met1[0]; const setMet1 = _met1[1];
  const _met2 = useState(""); const met2 = _met2[0]; const setMet2 = _met2[1];
  const _met3 = useState(""); const met3 = _met3[0]; const setMet3 = _met3[1];
  const _stak = useState([{ id: 1, name: "Jennifer Park", role: "Director of IT Security", stance: "Champion", notes: "ZT program lead" }]); const stak = _stak[0]; const setStak = _stak[1];
  const _gttSvc = useState([{ id: 1, name: "Managed SASE", status: "", notes: "" }, { id: 2, name: "Managed SSE", status: "", notes: "" }, { id: 3, name: "ZTNA", status: "", notes: "" }, { id: 4, name: "Managed Firewall", status: "", notes: "" }, { id: 5, name: "DDoS Protection", status: "", notes: "" }, { id: 6, name: "MDR", status: "", notes: "" }]); const gttSvc = _gttSvc[0]; const setGttSvc = _gttSvc[1];
  const _comp = useState([{ id: 1, label: "SOC 2 Type II", applicable: false, notes: "" }, { id: 2, label: "HIPAA", applicable: false, notes: "" }, { id: 3, label: "PCI-DSS", applicable: true, notes: "4 payment processing sites" }, { id: 4, label: "NIST CSF", applicable: false, notes: "" }, { id: 5, label: "GDPR", applicable: false, notes: "" }, { id: 6, label: "State Privacy Laws", applicable: false, notes: "" }]); const comp = _comp[0]; const setComp = _comp[1];
  const _compUrg = useState(""); const compUrg = _compUrg[0]; const setCompUrg = _compUrg[1];
  const saseAvg = (sase.reduce(function (a, x) { return a + x.score; }, 0) / sase.length).toFixed(1);

  return (<div style={{ display: "flex", flexDirection: "column", gap: 14 }}><SecHead s={SECS.find(function(x){return x.id==="security";})} />
    <Strip label="Security Tower" pct={58} color={T.red} detail={secTools.length + " tools · " + vendors.filter(function (v) { return v.decision === "Replace"; }).length + " to replace"} />
    <Disc tag="TRIGGER" tagColor={T.red} title="Compelling event" summary="Why are we here?" defaultOpen={true}>
      <Decision question="What's driving this conversation?" options={["PANW Renewal Cost", "Key Personnel Loss", "Board Mandate", "Compliance Gap", "M&A Integration", "Cost Reduction"]} selected={trigger} onSelect={setTrigger} color={T.red} />
      <textarea value={trigNote} onChange={function (e) { setTrigNote(e.target.value); }} style={Object.assign({}, smI, { width: "100%", minHeight: 60, resize: "vertical", marginTop: 10, lineHeight: 1.5, boxSizing: "border-box" })} placeholder="Why now? What's prompting this evaluation? (e.g., subscription renewal is expensive, lost key security personnel, new direction to reduce costs)" />
    </Disc>
    <Disc tag="SUCCESS VISION" tagColor={T.green} title="1-year outcomes" summary="What does success look like?">
      <span style={{ fontFamily: T.f, fontSize: 12, color: T.td, marginBottom: 6, display: "block" }}>Fast-forward 1 year after successful implementation — what&apos;s different?</span>
      <textarea value={vision} onChange={function (e) { setVision(e.target.value); }} style={Object.assign({}, smI, { width: "100%", minHeight: 70, resize: "vertical", lineHeight: 1.5, boxSizing: "border-box" })} placeholder="How does it affect the business? The department? What's the board saying?" />
      <div style={{ marginTop: 12 }}><span style={{ fontFamily: T.f, fontSize: 11, fontWeight: 500, color: T.td, display: "block", marginBottom: 6 }}>Key success metrics:</span><div style={{ display: "flex", gap: 8 }}><input value={met1} onChange={function (e) { setMet1(e.target.value); }} placeholder="Metric 1 (e.g., incidents/month)" style={Object.assign({}, smI, { flex: 1, boxSizing: "border-box" })} /><input value={met2} onChange={function (e) { setMet2(e.target.value); }} placeholder="Metric 2 (e.g., response time)" style={Object.assign({}, smI, { flex: 1, boxSizing: "border-box" })} /><input value={met3} onChange={function (e) { setMet3(e.target.value); }} placeholder="Metric 3 (e.g., compliance score)" style={Object.assign({}, smI, { flex: 1, boxSizing: "border-box" })} /></div></div>
    </Disc>
    <Disc tag="STAKEHOLDERS" tagColor={T.teal} title="Leadership alignment" summary={stak.length + " tracked \u00b7 " + stak.filter(function (x) { return x.stance === "Champion"; }).length + " champions"}>
      {stak.map(function (x, i) { return (<div key={x.id} style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 0", borderBottom: i < stak.length - 1 ? "1px solid " + T.border : "none" }}><input value={x.name} onChange={function (e) { setStak(stak.map(function (s, j) { return j === i ? Object.assign({}, s, { name: e.target.value }) : s; })); }} style={Object.assign({}, smI, { width: 120, fontSize: 11 })} /><select value={x.role} onChange={function (e) { setStak(stak.map(function (s, j) { return j === i ? Object.assign({}, s, { role: e.target.value }) : s; })); }} style={Object.assign({}, selS, { fontSize: 10 })}>{["CISO", "CTO", "CIO", "VP of IT Security", "Director of IT Security", "Sr. Security Architect", "Security Engineer", "Compliance Manager", "Other"].map(function (o) { return <option key={o}>{o}</option>; })}</select><select value={x.stance} onChange={function (e) { setStak(stak.map(function (s, j) { return j === i ? Object.assign({}, s, { stance: e.target.value }) : s; })); }} style={Object.assign({}, selS, { fontSize: 10, color: x.stance === "Champion" ? T.green : x.stance === "Blocker" ? T.red : x.stance === "Supporter" ? T.cyan : T.td })}>{["Champion", "Supporter", "Neutral", "Blocker"].map(function (o) { return <option key={o}>{o}</option>; })}</select><input value={x.notes} onChange={function (e) { setStak(stak.map(function (s, j) { return j === i ? Object.assign({}, s, { notes: e.target.value }) : s; })); }} placeholder="Notes" style={Object.assign({}, smI, { flex: 1, fontSize: 10 })} /></div>); })}
      <button onClick={function () { setStak(stak.concat([{ id: Date.now(), name: "", role: "Other", stance: "Neutral", notes: "" }])); }} style={{ fontFamily: T.f, fontSize: 11, color: T.teal, background: T.teal + "08", border: "1px dashed " + T.teal + "33", borderRadius: 5, padding: "6px 14px", cursor: "pointer", marginTop: 8, width: "100%" }}>+ Add stakeholder</button>
    </Disc>
    <Nts tag="SECURITY NOTES" tc={T.red} title="Session Notes" sub="Posture, ZT, vendor decisions" value={notes} onChange={setNotes} rows={5} />
    <AIBtn label="Full security posture analysis" color={T.red} data={{ trigger: trigger, triggerNotes: trigNote, successVision: vision, successMetrics: { m1: met1, m2: met2, m3: met3 }, stakeholders: stak, notes: notes, sase: sase, gttServices: gttSvc, vendors: vendors, zt: zt, compliance: comp, complianceUrgency: compUrg, securityDecisions: { saseChoice: sd1, ztApproach: sd2 }, findings: secFindings }} />

    <PrimaryCard tag="DECISIONS" tagColor={T.amber} title="Security strategy">
      <Decision question="SASE Platform?" options={["FortiSASE", "Zscaler", "Hybrid", "Evaluate"]} selected={sd1} onSelect={setSd1} color={T.red} />
      <div style={{ borderTop: "1px solid " + T.border }} />
      <Decision question="ZT approach?" options={["Identity-First", "Network-First", "Converged", "Phased"]} selected={sd2} onSelect={setSd2} color={T.red} />
    </PrimaryCard>

    <Disc tag="SASE/SSE" tagColor={T.violet} title="SASE readiness" summary={"Avg: " + saseAvg + " / 5"} right={<span style={{ fontFamily: T.f, fontSize: 16, fontWeight: 700, color: saseAvg >= 3 ? T.amber : T.red }}>{saseAvg}</span>}>
      {sase.map(function (x, i) { return <div key={i} style={{ borderBottom: i < sase.length - 1 ? "1px solid " + T.border : "none" }}><ScoreRow label={x.label} score={x.score} onChange={function (v) { setSase(sase.map(function (s, j) { return j === i ? Object.assign({}, s, { score: v }) : s; })); }} color={T.violet} /></div>; })}
    </Disc>
    <Disc tag="GTT PORTFOLIO" tagColor={T.cyan} title="GTT service mapping" summary={gttSvc.filter(function (x) { return x.status === "Proposed"; }).length + " proposed \u00b7 " + gttSvc.filter(function (x) { return x.status === "Evaluate"; }).length + " evaluating"}>
      {gttSvc.map(function (x, i) { return (<div key={x.id} style={{ display: "flex", alignItems: "center", gap: 10, padding: "9px 0", borderBottom: i < gttSvc.length - 1 ? "1px solid " + T.border : "none" }}><span style={{ fontFamily: T.f, fontSize: 12, fontWeight: 500, color: T.tp, width: 130 }}>{x.name}</span><div style={{ display: "flex", gap: 4 }}>{["Proposed", "Evaluate", "N/A"].map(function (opt) { var sel = x.status === opt; return <button key={opt} onClick={function () { setGttSvc(gttSvc.map(function (s, j) { return j === i ? Object.assign({}, s, { status: opt }) : s; })); }} style={{ fontFamily: T.f, fontSize: 10, padding: "3px 10px", borderRadius: 4, cursor: "pointer", border: "1.5px solid " + (sel ? T.cyan : T.border), background: sel ? T.cyan + "12" : "transparent", color: sel ? T.cyan : T.td, fontWeight: sel ? 600 : 400 }}>{opt}</button>; })}</div><input value={x.notes} onChange={function (e) { setGttSvc(gttSvc.map(function (s, j) { return j === i ? Object.assign({}, s, { notes: e.target.value }) : s; })); }} placeholder="Rationale / scope" style={Object.assign({}, smI, { flex: 1, fontSize: 10 })} /></div>); })}
    </Disc>
    <Disc tag="VENDORS" tagColor={T.amber} title="Consolidation matrix" summary={vendors.filter(function (v) { return v.decision === "Replace"; }).length + " to replace, " + vendors.filter(function (v) { return v.decision === "Retain"; }).length + " retain"}>
      {vendors.map(function (v, i) { return (<div key={i} style={{ display: "flex", alignItems: "center", gap: 10, padding: "8px 0", borderBottom: i < vendors.length - 1 ? "1px solid " + T.border : "none" }}><span style={{ fontFamily: T.f, fontSize: 12, fontWeight: 500, width: 100 }}>{v.name}</span><select value={v.decision} onChange={function (e) { setVendors(vendors.map(function (x, j) { return j === i ? Object.assign({}, x, { decision: e.target.value }) : x; })); }} style={Object.assign({}, selS, { fontSize: 10 })}>{["Retain", "Replace", "Evaluate", "Consolidate", "Defer"].map(function (o) { return <option key={o}>{o}</option>; })}</select><input value={v.reason} onChange={function (e) { setVendors(vendors.map(function (x, j) { return j === i ? Object.assign({}, x, { reason: e.target.value }) : x; })); }} style={Object.assign({}, smI, { flex: 1, fontSize: 10 })} placeholder="Rationale" /></div>); })}
    </Disc>
    <Disc tag="ZERO TRUST" tagColor={T.teal} title="ZT checklist" summary={zt.filter(function (x) { return x.done; }).length + "/" + zt.length + " ready"}>
      {zt.map(function (x, i) { return <div key={i} style={{ borderBottom: i < zt.length - 1 ? "1px solid " + T.border : "none" }}><Chk label={x.label} done={x.done} sub={x.sub} onToggle={function () { setZt(zt.map(function (c, j) { return j === i ? Object.assign({}, c, { done: !c.done }) : c; })); }} /></div>; })}
    </Disc>
    <Disc tag="COMPLIANCE" tagColor={T.amber} title="Compliance & regulatory" summary={comp.filter(function (x) { return x.applicable; }).length + " frameworks applicable"}>
      {comp.map(function (x, i) { return (<div key={x.id} style={{ display: "flex", alignItems: "flex-start", gap: 10, padding: "8px 0", borderBottom: i < comp.length - 1 ? "1px solid " + T.border : "none" }}><div onClick={function () { setComp(comp.map(function (c, j) { return j === i ? Object.assign({}, c, { applicable: !c.applicable }) : c; })); }} style={{ width: 18, height: 18, borderRadius: 3, border: "1.5px solid " + (x.applicable ? T.amber : T.border), background: x.applicable ? T.amber + "15" : "transparent", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 1 }}>{x.applicable ? <span style={{ fontSize: 11, color: T.amber, fontWeight: 700 }}>{"\u2713"}</span> : null}</div><div style={{ flex: 1 }}><span style={{ fontFamily: T.f, fontSize: 12, color: x.applicable ? T.tp : T.td }}>{x.label}</span><input value={x.notes} onChange={function (e) { setComp(comp.map(function (c, j) { return j === i ? Object.assign({}, c, { notes: e.target.value }) : c; })); }} placeholder="Scope / notes" style={Object.assign({}, smI, { width: "100%", fontSize: 10, marginTop: 4 })} /></div></div>); })}
      <div style={{ borderTop: "1px solid " + T.border, marginTop: 10, paddingTop: 10 }}><Decision question="Compliance urgency?" options={["Audit Imminent", "Annual Review", "Board Requirement", "Future Concern"]} selected={compUrg} onSelect={setCompUrg} color={T.amber} /></div>
    </Disc>
    <Disc tag="FINDINGS" tagColor={T.red} title="Security findings" summary={secFindings.length + " items"}><Findings items={secFindings} setItems={setSecFindings} placeholder="Add finding..." color={T.red} /></Disc>
    <Disc tag="INVENTORY" tagColor={T.red} title="Security tools" summary={secTools.length + " tools tracked"}><InvTable cols={SEC_COLS} rows={secTools} onRm={function (id) { setSecTools(secTools.filter(function (e) { return e.id !== id; })); }} color={T.red} /></Disc>
  </div>);
}

export default SecView;
